### ISSUE TITLE
main.pyを実行したときのエラー

### ISSUE THREAD

**Issue by tanakagainen** [nohararc/discord_voiceroid#11]
突然の質問失礼します。
記事を参考に読み上げbotを制作してみているものです。(初心者です)
voiceroid2(64bit)、python(64bit)の環境でmain.pyを実行するとbotはVCには入ってくるのですが
文字をいくら打っても以下のようなエラーが出て読み上げてくれません。
--------------------
Ignoring exception in on_message
Traceback (most recent call last):
  File "client.pyのpath", line 384, in _run_event
    await coro(*args, **kwargs)
  File "bot.pyのpath", line 44, in on_message
    source = discord.FFmpegPCMAudio(text2wav(self.vcroid, message.content))
  File "text2wav.pyのpath", line 29, in text2wav
    speech, tts_events = vc.textToSpeech(text)
  File "pyvcroid2.pyのpath", line 541, in textToSpeech
    kana = self.textToKana(text, timeout = timeout)
  File "pyvcroid2.pyのpath", line 403, in textToKana
    raise e
  File "pyvcroid2.pyのpath", line 390, in textToKana
    raise Exception(result)
Exception: ResultCode.INVALID_ARGUMENT
--------------------
解決法があれば教えていただきたいです。

(追加)
私のpcではpip install -r requirements.txtを実行した際に
ERROR: Could not find a version that satisfies the requirement pyvcroid2==0.21 (from versions: none)
ERROR: No matching distribution found for pyvcroid2==0.21
とのエラーが出ていたため[pyvcroid2]/[pyvcroid2]/__init__.pyを参考に
requirements.txt内のpyvcroid2==0.21をpyvcroid2==0.2.2に変更しました。

**Comment by nohararc** [comment]
@tanakagainen botの権限が怪しい気がします。

ここでプロンプトに読み取ったメッセージを出力するようにしていますが、何か出力されますか？
https://github.com/nohararc/discord_voiceroid/blob/master/bot.py#L43

botにテキストチャンネル読取り権限があるかご確認ください。

**Comment by tanakagainen** [comment]
返信ありがとうございます。
botにテキストチャンネル読取り権限はあるようです。

_ここでプロンプトに読み取ったメッセージを出力するようにしていますが、何か出力されますか？_
とありますがこれはどのように確認したらよいのでしょうか？

**Comment by nohararc** [comment]
コマンドプロンプト等で以下のような表示が出ると思います。

```
python main.py
ready
ここにテキストメッセージがでるはず
```

**Comment by tanakagainen** [comment]
C.....>main.pyのパス
ready

Ignoring exception in on_message
Traceback (most recent call last):
…
と続きます。
確かにテキストメッセージを読み込んでないみたいですね.....
botに管理者権限を与えても同じような状況です。
