### ISSUE TITLE
main.pyを実行した際のエラー？について

### ISSUE THREAD

**Issue by ibeibeai** [nohararc/discord_voiceroid#13]
ご質問失礼いたします。
main.pyを実行したところ下記が表示されました。

C:\Users\Users\Downloads\discord_voiceroid-master>python main.py
Traceback (most recent call last):
  File "C:\Users\Users\Downloads\discord_voiceroid-master\main.py", line 43, in <module>
    main()
  File "C:\Users\Users\Downloads\discord_voiceroid-master\main.py", line 10, in main
    vc = pyvcroid2.VcRoid2()
  File "C:\Users\Users\AppData\Local\Programs\Python\Python39-32\lib\site-packages\pyvcroid2\pyvcroid2.py", line 102, in __init__
    raise Exception(result)
Exception: ResultCode.LICENSE_ABSENT

こちらの
Exception: ResultCode.LICENSE_ABSENT
についてどのような対処が必要であるかご教示願いたいです。

環境は参考にさせていただいた通り下記になります。
Windows10 64bit
Python3.9.1(32bit)
VOICEROID2

突然の質問で大変申し訳ございませんがご確認いただけますでしょうか。
よろしくお願いいたします。

**Comment by nohararc** [comment]
pyvcroid2側でのエラーなのでまずはサンプルが動作するかご確認ください
https://github.com/Nkyoku/pyvcroid2/blob/main/sample.py

**Comment by ibeibeai** [comment]
上記sample.pyを実行し、下記が表示されました。

C:\Users\Users\Downloads>python sample.py
Traceback (most recent call last):
  File "C:\Users\Users\Downloads\sample.py", line 21, in <module>
    with pyvcroid2.VcRoid2() as vc:
  File "C:\Users\Users\AppData\Local\Programs\Python\Python39-32\lib\site-packages\pyvcroid2\pyvcroid2.py", line 102, in __init__
    raise Exception(result)
Exception: ResultCode.LICENSE_ABSENT

質問と同じようにエラーが表示されるようです。

実行の仕方等、間違っている箇所があればご指摘していただけますと幸いです。

**Comment by nohararc** [comment]
pyvcroid2側のエラーになるので私のほうではわかりません。

**Comment by ibeibeai** [comment]
再度質問失礼いたします。
一からインストールし直したところ下記のエラーが表示されました。

C:\Users\Users\Downloads\discord_voiceroid-master>python main.py
Traceback (most recent call last):
  File "C:\Users\Users\Downloads\discord_voiceroid-master\main.py", line 43, in <module>
    main()
  File "C:\Users\Users\Downloads\discord_voiceroid-master\main.py", line 32, in main
    bot = commands.Bot(command_prefix=commands.when_mentioned_or("."))
TypeError: __init__() missing 1 required keyword-only argument: 'intents'

何度もご質問する形となり大変申し訳ございませんがご教示頂けますでしょうか。
