### ISSUE TITLE
コマンド式

### ISSUE THREAD

**Issue by nyanham** [nohararc/discord_voiceroid#6]
このボットにコマンドを加えるのはどうでしょうか。例えば　!vrjoin を打ったら、その打ったチャンネルのチャットを読み上げて、打ったユーザーがいるVCで読み上げるとか、!vcleave で切断するとか、結構便利になると思います！
後は、もしVCに誰もいなくなったら、自動的に切断する機能も捨てがたいですね！

**Comment by nyanham** [comment]
ちょっと bot.py をいじってコマンド式にしようとしたが、こういうの初めてでうまくできませんでした…
ボットを呼ぶまでは出たんだけど、読み上げがうまくいきません…
良かったら参考にどうぞ！

エラーメッセージは：
```
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\rafae\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "D:\rafae\Documents\ツール\discord_voiceroid-master - コピー\bot.py", line 43, in on_message
    while self.voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'
```

bot.py:
```
from ui import SelectTextChannel, SelectVoiceChannel
import discord
import asyncio

from discord.ext import commands
from text2wav import text2wav
from Item import Item
import pyvcroid2
pyvcroid2.VcRoid2(install_path="C:\Program Files (x86)\AHS\VOICEROID2", install_path_x86="C:\Program Files (x86)\AHS\VOICEROID2")

client = commands.Bot(command_prefix='.')
voice_client = None


class VoiceroidTTSBot(commands.Cog):
    def __init__(self, client, vc):
        self.client: commands.Bot = client
        self.vcroid: pyvcroid2.VcRoid2 = vc
        self.voice_channel: discord.VoiceChannel = None	
        self.voice_client: discord.VoiceClient = None


    @client.command()
    async def join(self, ctx):
        print('#voicechannelを取得')
        vc = ctx.author.voice.channel
        print('#voicechannelに接続')
        await vc.connect()

    @client.command()
    async def bye(self, ctx):
        print('#切断')
        await ctx.voice_client.disconnect()

    @commands.Cog()
    async def on_message(self, message):
        if message.content.startswith('.'):
            pass

        else:
            if message.guild.voice_client:
                print(message.content)
                while self.voice_client.is_playing():
                    await asyncio.sleep(0.1)
                source = discord.FFmpegPCMAudio(text2wav(self.vcroid, message.content))
                self.voice_client.play(source)
```

**Comment by nohararc** [comment]
@nyanham ありがとうございます、デコレータの部分が間違ってそうですね。実装するときは参考にさせていただきます。
