### ISSUE TITLE
実行エラーに関する質問

### ISSUE THREAD

**Issue by ghost** [nohararc/discord_voiceroid#8]
突然の質問失礼します。
コマンドプロンプトにてpython main.pyを実行したところ、以下のようなエラー文が表示されました。お手数ですが、どのようなエラーなのか教えていただけないでしょうか？
私の環境では64bitのpythonを用いたためvoiceroid2も64bitに変更しています。

Traceback (most recent call last):
  File "main.pyが格納されているフォルダのパス", line 43, in <module>
    main()
  File "main.pyが格納されているフォルダのパス", line 13, in main
    vc.loadLanguage("standard")
  File "pyvcroid2.pyが格納されているフォルダのパス", line 174, in loadLanguage
    raise Exception(result)
Exception: ResultCode.READ_FAULT

**Comment by nohararc** [comment]
Nkyoku/pyvcroid2を呼び出す部分でエラー出ている？ようですね。

https://github.com/Nkyoku/pyvcroid2/blob/main/sample.py 単体で動作するかお試しください。
